local tbl = 
{
	AstE10sDivinationDriftA = false,
	AstE10sDivinationDriftB = false,
	AstE10sDivinationDriftC = false,
	AstE10sDivinationDriftD = false,
	AstE10sDivinationDriftE = false,
	AstE10sKb = true,
	AstE10sPots = false,
	AstE10sSaveCiA = false,
	AstE10sSaveCiB = false,
	AstE10sSaveCiC = false,
	AstE10sSaveCiD = false,
	AstE10sSaveEdA = false,
	AstE10sSaveEdB = false,
	AstE10sSaveEdC = false,
	AstE10sSaveEdD = false,
	AstE10sUseLs = true,
	AstE11sCycleAh = true,
	AstE11sDivinationDriftA = false,
	AstE11sKb = true,
	AstE11sPots = false,
	AstE11sPrep = true,
	AstE11sReopenerPot = false,
	AstE11sTetherCi = true,
	AstE11sTetherEd = true,
	AstE11sUseLs = true,
	AstE11sUseLsReopener = false,
	AstE12sKbDia = true,
	AstE12sKbLion = true,
	AstE9sDivinationDriftA = false,
	AstE9sDivinationDriftB = false,
	AstE9sDivinationDriftC = false,
	AstE9sKb = true,
	AstE9sPots = false,
	AstE9sSaveCiA = false,
	AstE9sSaveCiB = false,
	AstE9sSaveCiC = false,
	AstE9sSaveCiD = false,
	AstE9sSaveEdA = false,
	AstE9sSaveEdB = false,
	AstE9sSaveEdC = false,
	AstE9sSaveEdD = false,
	AstE9sUseLs = true,
	AstEvHotbar = 
	{
		Dungeon = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Esuna = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Heal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Neutral = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyAb = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyAh = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyB = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyBII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyCo = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyCu = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyEd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyH = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyHeals = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyHo = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Star = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankAb = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankB = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankBII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankCi = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankEd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		UsePrepull = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
	},
	AstEvHotbarBgT = 255,
	AstEvHotbarButColOff = 
	{
		B = 0.39215686917305,
		G = 0.39215686917305,
		R = 0.39215686917305,
		T = 1,
	},
	AstEvHotbarButColOn = 
	{
		B = 0,
		G = 0,
		R = 0.39215686917305,
		T = 1,
	},
	AstEvHotbarButtonSizeX = 103,
	AstEvHotbarButtonSizeY = 30,
	AstEvHotbarColumns = 1,
	AstEvHotbarEnabled = true,
	AstEvHotbarLocked = false,
	AstEvPartyOverhealAoe = 30,
	AstEvPartyOverhealEd = 30,
	AstEvPartyOverhealSingle = 30,
	AstEvTankOverhealCi = 30,
	AstEvTankOverhealEd = 30,
	AstEvTankOverhealSingle = 30,
	AstSavHotbar = 
	{
		Heal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyAb = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyAh = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyB = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyBII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyCo = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyCu = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyEd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyH = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyHeals = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyHo = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyNeutral = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyStar = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankAb = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankB = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankBII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankCi = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankEd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		UseNSPrepull = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		UsePrepull = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
	},
	AstSavHotbarBgT = 255,
	AstSavHotbarButColOff = 
	{
		B = 0.39215686917305,
		G = 0.39215686917305,
		R = 0.39215686917305,
		T = 1,
	},
	AstSavHotbarButColOn = 
	{
		B = 0,
		G = 0,
		R = 0.39215686917305,
		T = 1,
	},
	AstSavHotbarButtonSizeX = 103,
	AstSavHotbarButtonSizeY = 30,
	AstSavHotbarColumns = 1,
	AstSavHotbarEnabled = true,
	AstSavHotbarLocked = false,
	AstSavPartyOverhealAoe = 30,
	AstSavPartyOverhealSingle = 30,
	AstSavTankOverheal = 30,
	CalloutE12sNumber = true,
	DrawE10sSides = true,
	DrawE11sElemental = true,
	DrawE12sDebuffs = true,
	DrawE12sKB = true,
	DrawE12sShiva = true,
	DrawE12sSpiritTaker = true,
	DrawE5sChainLightning = true,
	DrawE5sClouds = true,
	DrawE6sFoot = true,
	DrawE6sOrbs = true,
	DrawE8sHead = true,
	DrawE8sOrbs = true,
	DrawE8sWings = true,
	DrawE9sSeeds = true,
	DrawE9sWaAa = true,
	DrawHotbar = true,
	ReactionVerLocal = "0.2.9",
	SchE10sCsDriftA = false,
	SchE10sCsDriftB = false,
	SchE10sCsDriftC = false,
	SchE10sCsDriftD = false,
	SchE10sCsDriftE = false,
	SchE10sKb = true,
	SchE10sManageNaturalED = true,
	SchE10sPots = false,
	SchE10sSaveExcoA = false,
	SchE10sSaveExcoB = false,
	SchE10sSaveExcoC = false,
	SchE10sSaveExcoD = false,
	SchE10sUseDiss = true,
	SchE11sCsDriftA = false,
	SchE11sCycleShield = true,
	SchE11sKb = true,
	SchE11sManageNaturalED = false,
	SchE11sPots = false,
	SchE11sReopenerPot = false,
	SchE11sSaveWhisp = true,
	SchE11sTetherExco = true,
	SchE11sUseDiss = true,
	SchE12sKbDia = true,
	SchE12sKbLion = true,
	SchE12sManageNaturalED = false,
	SchE12sP2ManageNaturalED = false,
	SchE12sP2UseDiss = true,
	SchE12sUseDiss = true,
	SchE9sCsDriftA = false,
	SchE9sCsDriftB = false,
	SchE9sCsDriftC = false,
	SchE9sKb = true,
	SchE9sManageNaturalED = false,
	SchE9sPots = false,
	SchE9sSaveExcoA = false,
	SchE9sSaveExcoB = false,
	SchE9sSaveExcoC = false,
	SchE9sSaveExcoD = false,
	SchE9sUseDiss = true,
	SchEvHotbar = 
	{
		Dungeon = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Esuna = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Heal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyAdlo = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyAp = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyConsolation = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyFeyB = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyIndom = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyLustrate = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyPhysick = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartySuccor = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyWhisp = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Seraph = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Soil = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankAdlo = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankAp = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankEt = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankExco = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankLustrate = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankPhysick = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		UsePrepull = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
	},
	SchEvHotbarBgT = 255,
	SchEvHotbarButColOff = 
	{
		B = 0.39215686917305,
		G = 0.39215686917305,
		R = 0.39215686917305,
		T = 1,
	},
	SchEvHotbarButColOn = 
	{
		B = 0,
		G = 0,
		R = 0.39215686917305,
		T = 1,
	},
	SchEvHotbarButtonSizeX = 103,
	SchEvHotbarButtonSizeY = 30,
	SchEvHotbarColumns = 1,
	SchEvHotbarEnabled = false,
	SchEvHotbarLocked = false,
	SchEvPartyOverhealAoe = 30,
	SchEvPartyOverhealSingle = 30,
	SchEvTankOverhealSingle = 30,
	SchSavHotbar = 
	{
		DeploymentTact = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		FeyIllu = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Heal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyAdlo = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyAp = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyConsolation = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyFeyB = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyIndom = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyLustrate = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyPhysick = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartySuccor = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyWhisp = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PlacePet = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Seraph = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Soil = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankAdlo = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankAp = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankEt = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankExco = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankLustrate = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankPhysick = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		UsePrepull = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
	},
	SchSavHotbarBgT = 255,
	SchSavHotbarButColOff = 
	{
		B = 0.39215686917305,
		G = 0.39215686917305,
		R = 0.39215686917305,
		T = 1,
	},
	SchSavHotbarButColOn = 
	{
		B = 0,
		G = 0,
		R = 0.39215686917305,
		T = 1,
	},
	SchSavHotbarButtonSizeX = 103,
	SchSavHotbarButtonSizeY = 30,
	SchSavHotbarColumns = 1,
	SchSavHotbarEnabled = true,
	SchSavHotbarLocked = false,
	SchSavPartyOverhealAoe = 2,
	SchSavPartyOverhealSingle = 0,
	WhmE10sKb = true,
	WhmE10sPomDriftA = true,
	WhmE10sPots = true,
	WhmE11sCycleMed = true,
	WhmE11sKb = true,
	WhmE11sPotDriftA = true,
	WhmE11sPots = true,
	WhmE11sReopenerPot = true,
	WhmE11sTetherRegen = true,
	WhmE12sKbDia = true,
	WhmE12sKbLion = true,
	WhmE9sKb = true,
	WhmE9sPomDriftA = true,
	WhmE9sPomDriftB = true,
	WhmE9sPots = true,
	WhmEvHotbar = 
	{
		Asylum = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		Dungeon = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		Esuna = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		Heal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyBene = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyCure = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyCureII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyCureIII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyMed = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyMedII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyRap = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyRegen = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartySol = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		PartyTetra = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		Plenary = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		TankBene = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		TankCure = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		TankCureII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		TankHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		TankLily = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		TankRegen = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		TankSol = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		TankTetra = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		Temperance = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
		UsePrepull = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = true,
		},
	},
	WhmEvHotbarBgT = 255,
	WhmEvHotbarButColOff = 
	{
		B = 0.39215686917305,
		G = 0.39215686917305,
		R = 0.39215686917305,
		T = 1,
	},
	WhmEvHotbarButColOn = 
	{
		B = 0,
		G = 0,
		R = 0.39215686917305,
		T = 1,
	},
	WhmEvHotbarButtonSizeX = 103,
	WhmEvHotbarButtonSizeY = 30,
	WhmEvHotbarColumns = 1,
	WhmEvHotbarEnabled = false,
	WhmEvHotbarLocked = false,
	WhmEvPartyOverhealAoe = 30,
	WhmEvPartyOverhealSingle = 30,
	WhmEvTankOverhealSingle = 5,
	WhmSavHotbar = 
	{
		Asylum = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Heal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyCure = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyCureII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyCureIII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyGcd = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyMed = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyMedII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyRap = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyRegen = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartySol = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		PartyTetra = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Plenary = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankBene = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankCure = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankCureII = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankHeal = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankLily = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankRegen = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankSol = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		TankTetra = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		Temperance = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
		UsePrepull = 
		{
			bool = true,
			key = -1,
			keyname = "None",
			modifierA = false,
			modifierC = false,
			modifierS = false,
			visible = false,
		},
	},
	WhmSavHotbarBgT = 255,
	WhmSavHotbarButColOff = 
	{
		B = 0.39215686917305,
		G = 0.39215686917305,
		R = 0.39215686917305,
		T = 1,
	},
	WhmSavHotbarButColOn = 
	{
		B = 0,
		G = 0,
		R = 0.39215686917305,
		T = 1,
	},
	WhmSavHotbarButtonSizeX = 103,
	WhmSavHotbarButtonSizeY = 30,
	WhmSavHotbarColumns = 1,
	WhmSavHotbarEnabled = true,
	WhmSavHotbarLocked = false,
	WhmSavPartyOverhealAoe = 5,
}



return tbl